### ISSUE TITLE
About the evaluation code

### ISSUE THREAD

**Issue by Lauch1ng** [h-zhao1997/cobra#3]
Hi! Will you release the evaluation code for Cobra? (e.g., evaluation on benchmarks like text-vqa, pope, etc.)  Thanks a lot.

**Comment by h-zhao1997** [comment]
I'm sorry, but we currently have no plans to release the evaluation code. However, it should be relatively straightforward to replicate the evaluation for Cobra based on open-source codes, such as the codebase of LLaVA.
