### ISSUE TITLE
No such file or directory: '.hf_token'

### ISSUE THREAD

**Issue by WenjunHuang94** [h-zhao1997/cobra#6]
No such file or directory: '.hf_token'. How should I solve it?
![image](https://github.com/h-zhao1997/cobra/assets/20516638/d591635d-711e-4087-89b6-73c4b1692c48)

![image](https://github.com/h-zhao1997/cobra/assets/20516638/5b88ef42-b72b-4ee9-99a0-6bd8587c9ae1)

**Comment by h-zhao1997** [comment]
Create a file named .hf_token and simply copy your Huggingface token into it.

**Comment by WenjunHuang94** [comment]
Is it downloading this file and naming it. hf_token? 
![image](https://github.com/h-zhao1997/cobra/assets/20516638/bcb6f690-cc61-4b03-a45b-dcf9d4c29643)

The error message after execution is as follows:
![image](https://github.com/h-zhao1997/cobra/assets/20516638/7c2e8f9a-607a-43de-8864-223d96503dc7)

**Comment by WenjunHuang94** [comment]
If it's convenient, may I add your WeChat account? I am very interested in your research and would like to seek your advice and exchange ideas. My WeChat: q785941939

**Comment by xingyifei2016** [comment]
I am also experiencing this problem. What is the huggingface token you are referring to?

**Comment by h-zhao1997** [comment]
@huangwenjunlovedy @xingyifei2016 Access token of your huggingface account

**Comment by WenjunHuang94** [comment]
@h-zhao1997 我配置后，发现会提示MambaConfig有问题。
![5e5d6dfa376f9f3698795272db3c374](https://github.com/h-zhao1997/cobra/assets/20516638/86e5bfbb-38af-46f0-aa02-50c2706c8689)

上面提示的MambaConfig不存在norm_epsilon属性，我调试跟了下，发现这里获取到的MambaConfig确实不满足后续程序的要求。请问是什么原因呢？我在base_llm.py +132行处，hf_pub_path值和hf_token值如下。难道是这两个值中的hf_token值不对导致的差异吗？
![ae891b4e68b40ba1c7f4809e7a79cac](https://github.com/h-zhao1997/cobra/assets/20516638/64115509-f94b-43d3-9be1-7a131cd20b4d)
![image](https://github.com/h-zhao1997/cobra/assets/20516638/76cfa60c-d8d3-4e7b-9afa-20999ab624cd)

**Comment by h-zhao1997** [comment]
@huangwenjunlovedy 应该在你的profile-access tokens中找到或新建一个token，token是以hf_开头的一串字符
